DROP TABLE IF EXISTS demoUsers;
DROP TABLE IF EXISTS secretstuff;

BEGIN;

CREATE TABLE demoUsers(
  user_id SERIAL PRIMARY KEY,
  username VARCHAR NOT NULL UNIQUE,
  password VARCHAR NOT NULL UNIQUE
);

CREATE TABLE secretstuff(
  secre_id SERIAL PRIMARY KEY,
  mySecret VARCHAR NOT NULL,
  myotherSecret VARCHAR NOT NULL
);

COMMIT;
